### ISSUE TITLE
Mismatch between input and output size distributions

### ISSUE THREAD

**Issue by bertrand-faure** [CalebBell/fluids#24] opened 2019-01-16 10:12 UTC
Hi,

I've started using your library to convert size distributions of nanoparticles across different basis (mass <-> surface <-> number). Somehow I have a mismatch between the input data (artificial distribution with 2 modes, equally-represented in mass) and the output plots (result of ParticleSizeDistribution.plot_pdf):
- the height of the modes in the mass-weighted fractions changes (the input fractions were normalized, so there should be no change)
- with a bimodal distribution, the proportions of the 2 modes provided as input on a mass basis correspond to the plot of the pdf in surface basis... I've provided a minimal example below.

The first issue could be related to a lack of renormalization of the fractions by the bin width (that would introduce a scaling factor over the whole pdf). For the 2nd issue, I've been browsing the code but could find why.
Thanks for your help.

Cheers,
Bertrand

See minimal example here:
https://gist.github.com/bertrand-faure/701fe217104a26b4bcc6ffb4c46c2b31

**Comment by CalebBell** [comment] 2019-01-17 00:38
Hi Bertrand,

Interesting issues you've encountered. The first thing I note is that the monotonically increasing interpolator used for curves by default is not performing well at all for bimodal distributions! I strongly recommend you set monotonic=False in the constructor of the PSD. Maybe I'll have to change the default, or look into multimodal distributions more. 

The second thing I notice is that the pdf plot isn't actually plotting the exact PDF; it's taking differences of the CDF and plotting that instead. I remember thinking about that when I was coding it, but I'm not sure why I went with that at the time. I will fix that bug in the plot - you can fix it in your own installation using the section of code at the bottom.  

I'll include the fix in the next release of fluids!

Please let me know if these two fixes don't solve your issues. I appreciate your concise code snippet; but I may still have missed something.

Sincerely,
Caleb

Fixed code in particle_size_distributions.py 's class ParticleSizeDistributionContinuous's method plot_pdf:
```
	def plot_pdf(self, n=(0, 1, 2, 3), d_min=None, d_max=None, pts=500):  # pragma: no cover
		try:
			import matplotlib.pyplot as plt
		except:  # pragma: no cover
			raise Exception(NO_MATPLOTLIB_MSG)            
		ds = self.ds_discrete(d_min=d_min, d_max=d_max, pts=pts)
		try:
			for ni in n:
				fractions = [self.pdf(d, n=ni) for d in ds]
#                fractions = self.fractions_discrete(ds=ds, n=ni) # Incorrect/bad code
				plt.semilogx(ds, fractions, label=_label_distribution_n(ni))
		except:
			fractions = [self.pdf(d, n=n) for d in ds]
#            fractions = self.fractions_discrete(ds=ds, n=n) # Incorrect/bad code
			plt.semilogx(ds, fractions, label=_label_distribution_n(n))
		plt.ylabel('Probability density function, [-]')
		plt.xlabel('Particle diameter, [m]')
		plt.title('Probability density function of %s distribution with '
				  'parameters %s' %(self.name, self.parameters))
		plt.legend()
		plt.show()

```

**Comment by CalebBell** [comment] 2019-01-22 03:09
Hi Bertrand,

I see the second issue now. It was confusing enough, and is caused by two different terms with the acronym PSD. The plot_pdf function is plotting the "probability density function", which has a mathematical definition. Its only relation to summing to 1 is that, when integrated over the entire range of particle sizes, the sum is 1. When working with nanoparticles, it will always have a huge magnitude.

What you want to plot is the "particle size distribution"; which was a little also what I wanted to plot when I wrote the function. I didn't distinguish between them at the time and so didn't write either correctly.
Fortunately, they are very easily converted - simply taking the set of points, summing them, and dividing each point by the sum.

I am adding the "normalized" keyword to plot_pdf, to make it plot the "particle size distribution" which sums to one. I've pushed the changes to [Github (on a branch)](https://github.com/CalebBell/fluids/blob/mergespa/fluids/particle_size_distribution.py#L1592); and they'll be in the next release. Accordingly, your example becomes:

```
fluids_psd = psd.ParticleSizeDistribution(ds=ds, fractions=fractions,  order=3, monotonic=False)

fluids_psd.plot_pdf((2,3), pts=len(ds), d_min=ds[0], d_max=ds[-1], normalized=True)
```

The slight difference in points is error from the cubic spline. You can easily avoid it by increasing the resolution - use 5000 points instead of 250, and you will have to zoom in to the plot very closely to tell the difference!
Cheers,
Caleb

**Comment by CalebBell** [comment] 2019-02-03 23:47
Fixed in release 0.1.74!
Cheers,
Caleb

**Closed by CalebBell** 2019-02-03 23:47 UTC

**Comment by bertrand-faure** [comment] 2019-02-12 11:22
Hi Caleb,

Thanks for your fix. I've tried the normalized version of the particle size distribution, and I've noticed 2 things which could be improved.
First thing is that the normalized distribution changes when one changes the resolution. For example, when comparing these 2 commands:

`fluids_psd.plot_pdf((3), pts=len(ds), d_min=ds[0], d_max=ds[-1], normalized=True)`

and

`fluids_psd.plot_pdf((3), pts=2*len(ds), d_min=ds[0], d_max=ds[-1], normalized=True)`

you will notice that increasing the resolution decreases the height of the peaks (as expected because the sum is bounded to 1). An improved version of the normalization routine would take the size resolution into account and normalize by the area under the psd. Another option would be to interpolate on the normalized fractions.

My second comment relates to the shifted peaks. Indeed, if you increase the resolution, the difference in peaks positions becomes negligible. Yet, my 'plot_pdf' command relies on the same size bins as the original data, so I expect that no interpolation is needed (I'm just querying the input data back with identical size sampling). To get the right overlap, one could feed the bin edges (ds + half the size resolution) to self.pdf, instead of the bin centers ds. The drawback is that we lose the 1st point, but that's to be expected when using a differentiation. I've modified plot_pdf below to get a good overlap in peak position compared to the input `plt.plot(ds, fractions, label='input Volume pdf')`:

`def plot_pdf(self, n=(0, 1, 2, 3), d_min=None, d_max=None, pts=500,
                 normalized=False, method='linear'):  # pragma: no cover
        r'''Plot the probability density function of the particle size 
        distribution. The plotted range can be specified using `d_min` and 
        `d_max`, or estimated automatically. One or more order can be plotted,
        by providing an iterable of ints as the value of `n` or just one int.
                
        Parameters
        ----------
        n : tuple(int) or int, optional
            None (for the `order` specified when the distribution was created),
            0 (number), 1 (length), 2 (area), 3 (volume/mass),
            or any integer; as many as desired may be specified, [-]
        d_min : float, optional
            Lower particle size diameter, [m]
        d_max : float, optional
            Upper particle size diameter, [m]
        pts : int, optional
            The number of points for values to be calculated, [-]
        normalized : bool, optional
            Whether to display the actual probability density function, which
            may have a huge magnitude - or to divide each point by the sum
            of all the points. Doing this is a common practice, but the values
            at each point are dependent on the number of points being plotted,
            and the distribution of the points;
            [-]
        method : str, optional
            Either 'linear', 'logarithmic', a Renard number like 'R10' or 'R5' 
            or'R2.5', or one of the sieve standards 'ISO 3310-1 R40/3', 
            'ISO 3310-1 R20', 'ISO 3310-1 R20/3', 'ISO 3310-1', 
            'ISO 3310-1 R10', 'ASTM E11', [-]
        '''
        try:
            import matplotlib.pyplot as plt
        except:  # pragma: no cover
            raise Exception(NO_MATPLOTLIB_MSG)           
        ds = self.ds_discrete(d_min=d_min, d_max=d_max, pts=pts, method=method)
        # Try adding half a bin to compensate for the cdf -> pdf differentiation
        bin_widths = np.array([ds[i+1] - ds[i] for i in range(len(ds)-1)])
        ds_shift = ds[:-1] + bin_widths/2
        try:
            for ni in n:
                fractions = [self.pdf(d, n=ni) for d in ds_shift]
                if normalized:
                    fractions = normalize(fractions)
                plt.semilogx(ds[1:], fractions, label=_label_distribution_n(ni))
        except Exception as e:
            fractions = [self.pdf(d, n=n) for d in ds_shift]
            if normalized:
                fractions = normalize(fractions)
            plt.semilogx(ds[1:], fractions, label=_label_distribution_n(n))
        plt.ylabel('Probability density function, [-]')
        plt.xlabel('Particle diameter, [m]')
        plt.title('Probability density function of %s distribution with '
                  'parameters %s' %(self.name, self.parameters))
        plt.legend()
        plt.show()
        return fractions`

Thanks for your feedback! There are probably much better ways to address these comments in your library, I've just provided some code for convenience.
Cheers,
Bertrand

**Comment by CalebBell** [comment] 2019-02-12 14:28
Hi Bertrand,

Your second comment is quite interesting! I'm thinking about it. 

I don't understand your first comment. As the number of bins increases, the amount in each bin always decreases. Can you provide a code sample describing what you are suggesting?

Cheers,
Caleb

**Comment by bertrand-faure** [comment] 2019-02-13 08:35
Hi Caleb,

Sure, you can find an example here:
https://gist.github.com/bertrand-faure/b500689b30bebcf3e6ac41387167415e
This code only works if all the bins have the same width, it has to be refined for non-uniform binning.

In the ISO convention on graphical representation of size distributions (you can find a preview here: https://www.sis.se/api/document/preview/616794/), the bin width is taken into account, so that distributions acquired on different instruments or under different conditions can be compared.

Let's imagine you have determined the size distribution of a powder with 2 different sets of sieves. The mass of particles collected in each sieve (i.e. size bin) will be different depending on the choice of the set of sieves. The total mass of powder will be the same in both experiments, but if you represent the mass on the y-axis you won't be able to overlay the distributions. If your size class is twice larger, the height of your size distribution with this representation will be twice larger as well. It makes it impossible to compare both measurements, which should overlap because you have characterized the same powder twice. One way around that is to represent the mass divided by the bin width on the y-axis. With such a representation, the mass collected by each sieve is given by the area under the curve, and both experiments can be compared.

I hope this explanation is less confusing, let me know if I'm not clear.

Cheers,
Bertrand
